/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.

*/

#include <stdio.h>
int main(){
	int fibo, fiboN, sum, aux;
	fibo = 1; // primeiro número Fibonacci.
	fiboN = 2; // segundo número Fibonacci
	sum = 0;   // soma de todos os números Fibonnacci pares e menores que 4.000.000.

	while(fiboN < 4000000){ //enquanto o ultimo termo for menor que 4.000.000
		if(fiboN%2==0){  // se o termo n+1 for par
			sum += fiboN;	// sum é incrementada pelo termo.
		}
		aux = fibo;	
		fibo = fiboN;
		fiboN += aux; // fiboN = aux + fiboN.

	}

	// imprime a soma de todos os numeros Fibonacci pares menores que 4.000.000.
	printf("%d\n", sum);

	return 0;
}